services:
    redis:
        image: redis:8-alpine
        container_name: shinro-redis
        ports:
            - "6379:6379"
        volumes:
            - redisdata:/data
        environment:
            - REDIS_ARGS=--requirepass shinro --appendonly yes

    db:
        image: postgres:16-alpine
        container_name: shinro-db
        environment:
            POSTGRES_USER: shinro
            POSTGRES_PASSWORD: shinro
            POSTGRES_DB: shinro
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
    redisdata:
