services:
    shinro.database:
        image: postgres:17-alpine
        container_name: shinro.database
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: shinro
            POSTGRES_PASSWORD: shinro
            POSTGRES_DB: shinro
        volumes:
            - postgres_data:/var/lib/postgresql/data

    shinro.cache:
        image: redis:8-alpine
        container_name: shinro.cache
        ports:
            - 6379:6379
        volumes:
            - redis_data:/data

volumes:
    postgres_data:
    redis_data:
