blockExoticSubdeps: true
minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude: []
trustPolicy: no-downgrade
audit-level: low
trustPolicyExclude:
    - "semver@6.3.1"
    - "prisma@7.10.0"
enablePrePostScripts: false
supportedArchitectures:
    os:
        - current
    cpu:
        - current

allowBuilds:
    "@parcel/watcher": false
    "@prisma/engines": false
    esbuild: false
    maplibre-gl: false
    prisma: false
    vue-demi: false
