blockExoticSubdeps: true
minimumReleaseAge: 1440 # 1 days
minimumReleaseAgeExclude: []
trustPolicy: no-downgrade
audit-level: low
trustPolicyExclude:
    - "chokidar@4.0.3"
    - "semver@6.3.1"
enablePrePostScripts: false
allowBuilds:
    "@parcel/watcher": false
    "@prisma/engines": false
    esbuild: false
    maplibre-gl: false
    prisma: false
    vue-demi: false
