blockExoticSubdeps: true
minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude: []
trustPolicy: no-downgrade
audit-level: low
trustPolicyExclude:
    - "semver@6.3.1"
enablePrePostScripts: false
allowBuilds:
    "@parcel/watcher": false
    "@prisma/engines": false
    esbuild: false
    maplibre-gl: false
    prisma: false
    sharp: false
    vue-demi: false
supportedArchitectures:
    os:
        - linux
        - current
    cpu:
        - x64
        - arm64
