name: Lint, Format, and Type-Check

on:
    push:
    pull_request:

jobs:
    lint-and-typecheck:
        runs-on: ubuntu-latest

        env:
            CI: true

        steps:
            - name: Checkout repository
              uses: actions/checkout@v7

            - name: Set up Node.js and PNPM
              uses: pnpm/setup@v2
              with:
                  version: ^11.20.0
                  runtime: node@24
                  install: false

            - name: Install dependencies
              run: pnpm clean-install

            - name: Run Linter
              run: pnpm lint

            - name: Run Formatter
              run: pnpm fmt

            - name: Run TypeScript Type Check
              run: pnpm typecheck
